x-agent: &agent
  volumes:
    - $VAULT_AGENT_CONFIG_FILEPATH:/vault/config.hcl
    - $VAULT_AGENT_TMPL_FILEPATH:/vault/vault-agent.json.tmpl

volumes:
  vault-vol:
  vault-logs:

networks:
  vault-network:

services:
  vault-dev:
    image: my-vault/vault:latest
    container_name: vault-dev
    build:
      context: .
      dockerfile: vault.Dockerfile
    environment:
      HISTIGNORE: "&:vault*"
      VAULT_DEV_LISTEN_ADDRESS: 0.0.0.0:8200
    command: "-dev -dev-root-token-id=root"
    cap_add:
      - IPC_LOCK
    ports:
      - 127.0.0.1:8200:8200
    networks:
      - vault-network

  vault-prod:
    image: my-vault/vault:latest
    build:
      context: .
      dockerfile: vault.Dockerfile
    environment:
      HISTIGNORE: "&:vault*"
    cap_add:
      - IPC_LOCK
    ports:
      - 127.0.0.1:8200:8200
    volumes:
      - vault-vol:/data
      - vault-logs:/logs/vault_audit.log
      - $VAULT_CONFIG_FILEPATH:/vault/config.hcl
    networks:
      - vault-network

  vault-agent:
    image: my-app/vault:latest
    build:
      context: .
      dockerfile: vault-agent.Dockerfile
    environment:
      HISTIGNORE: "&:vault*"
    <<: *agent
    networks:
      - vault-network