version: '3'

volumes:
  vault-vol:

networks:
  vault-network:

services:
  vault:
    image: my-app/vault:latest
    build:
      context: .
      dockerfile: vault.Dockerfile
    environment:
      - HISTIGNORE="&:vault*"
    command: ["-dev", "-dev-root-token-id=root"] # Dev setup, remove for prod
    ports:
      - 127.0.0.0:8200:8200
    volumes:
      - vault-vol:/data
      - $VAULT_CONFIG_FILEPATH:/vault/config.hcl
    networks:
      - vault-network

  vault-agent:
    image: my-app/vault:latest
    build:
      context: .
      dockerfile: vault-agent.Dockerfile
    environment:
      - HISTIGNORE="&:vault*"
    ports:
      - 127.0.0.0:8100:8100
    volumes:
      - ./vault-agent.tmpl:/vault/vault-agent.tmpl
      - $VAULT_AGENT_CONFIG_FILEPATH:/vault/config.hcl
      - ./tmp/roleid:/etc/vault/roleid
      - ./tmp/secretid:/etc/vault/secretid
    networks:
      - vault-network